[package]
name = "oxidezap-cli"
description = "Lightweight, scriptable WhatsApp CLI for OxideZap powered by usage-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "oxidezap-cli"
path = "src/main.rs"

[dependencies]
oxidezap-ipc = { workspace = true }
oxidezap-wire = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }
usage = { workspace = true }

[lints]
workspace = true
