//! "Is this still worth publishing?", asked of GitHub rather than of the
//! branch.
//!
//! Two different questions hide here and both need asking more than once.
//! Builds run in parallel, so the order two runs reach the publish job is the
//! order their *builds* finished rather than the order their commits were
//! pushed — a slower older build would otherwise replace the live site. And a
//! pull request can close while a publish is in flight, in which case the
//! preview has already been taken down and this run would put it back.
//!
//! Asking once could close neither window: the gap is between the answer and
//! the push. So the question is asked again before every attempt at the
//! branch, which is why it is a function here rather than a step in the
//! workflow.
//!
//! Where the shell wrote this to a file and handed the publisher a command to
//! run, it is now a value the publisher holds — which is what removes the
//! third and fourth `.sh` files from the tree: two generated by heredoc into
//! `$RUNNER_TEMP`, whose only job was to translate one set of exit codes into
//! another.

use crate::json;
use crate::util::{Error, Result, Run, env_or, need_env};
use crate::{err, note};

/// What the API says about the thing this run was started for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    /// Still the newest thing to say, and still wanted.
    Current,
    /// A newer run is publishing this target; what is up there is *newer*
    /// than ours.
    Superseded,
    /// The pull request is closed; its preview should not exist at all.
    Closed,
}

/// Which question a given write to the branch is conditional on.
///
/// The shell spelled these as three small scripts and a `case` translating
/// between two vocabularies; the case that was easy to lose there — an
/// operational failure collapsing into "not closed" — is a `Result` here and
/// cannot be.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Precondition {
    /// None: publish unconditionally. Not used by the workflow; here so a
    /// publish can be driven by hand.
    Always,
    /// Publishing: proceed only while this run is still the current one.
    StillCurrent,
    /// The compensating removal after a publish: proceed only if the pull
    /// request has closed since. Superseded is *not* a reason to remove — a
    /// newer run of the same pull request owns the preview, and deleting it
    /// would take down one that is wanted.
    NowClosed,
    /// The take-down job: proceed only while the pull request is still
    /// closed. A reopened one has a `reopened` run publishing its preview
    /// behind us.
    StillClosed,
}

/// Whether the write should happen.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Wanted {
    Yes,
    StandDown,
}

impl Precondition {
    pub fn parse(name: &str) -> Result<Self> {
        match name {
            "always" | "none" => Ok(Precondition::Always),
            "still-current" => Ok(Precondition::StillCurrent),
            "now-closed" => Ok(Precondition::NowClosed),
            "still-closed" => Ok(Precondition::StillClosed),
            other => Err(err!(
                "unknown check `{other}`: expected always, still-current, now-closed or still-closed"
            )),
        }
    }

    /// Ask. An `Err` is the question *breaking* — a network blip, a rate
    /// limit, an API 500 — and reading that as "stand down" is how a
    /// deployment silently does not happen while the job reports success and
    /// leaves nothing to retry. An unanswered question is not a no.
    pub fn ask(self, api: &Api) -> Result<Wanted> {
        match self {
            Precondition::Always => Ok(Wanted::Yes),
            Precondition::StillCurrent => match api.state()? {
                State::Current => Ok(Wanted::Yes),
                State::Superseded | State::Closed => Ok(Wanted::StandDown),
            },
            Precondition::NowClosed => match api.state()? {
                State::Closed => Ok(Wanted::Yes),
                State::Current | State::Superseded => Ok(Wanted::StandDown),
            },
            Precondition::StillClosed => {
                if api.pull_request_is_open()? {
                    note!("pull request was reopened; its preview is wanted again");
                    Ok(Wanted::StandDown)
                } else {
                    Ok(Wanted::Yes)
                }
            }
        }
    }
}

/// The repository, the run, and a token to ask with.
///
/// Read from the environment once, so a missing variable is one message at
/// startup rather than a curl invocation with an empty URL in it.
pub struct Api {
    token: String,
    repo: String,
    event: String,
    pr_number: String,
    pr_head: String,
    ref_name: String,
    sha: String,
}

impl Api {
    pub fn from_env() -> Result<Self> {
        Ok(Api {
            token: need_env("GH_TOKEN")?,
            repo: need_env("GITHUB_REPOSITORY")?,
            event: env_or("GITHUB_EVENT_NAME", ""),
            pr_number: env_or("PR_NUMBER", ""),
            pr_head: env_or("PR_HEAD", ""),
            ref_name: env_or("GITHUB_REF_NAME", ""),
            sha: env_or("GITHUB_SHA", ""),
        })
    }

    fn is_pull_request(&self) -> bool {
        self.event == "pull_request"
    }

    /// The three-way answer the publisher and the compensating removal both
    /// read, and the reason they read the same one: collapsing "superseded"
    /// into "closed" is how an older superseded build deletes the newer
    /// revision's perfectly good preview.
    pub fn state(&self) -> Result<State> {
        if self.is_pull_request() {
            let pr = self.get(&format!("pulls/{}", self.number()?))?;
            let state = field(&pr, "state")?;
            if state != "open" {
                note!("pull request is closed; its preview should not exist");
                return Ok(State::Closed);
            }
            let head = field(&pr, "head.sha")?;
            let want = &self.pr_head;
            if want.is_empty() {
                return Err(err!(
                    "PR_HEAD is required to tell this run from a newer one"
                ));
            }
            if &head != want {
                note!("head has moved; a newer run publishes it");
                return Ok(State::Superseded);
            }
            Ok(State::Current)
        } else {
            if self.ref_name.is_empty() || self.sha.is_empty() {
                return Err(err!(
                    "GITHUB_REF_NAME and GITHUB_SHA are required to tell this run from a newer one"
                ));
            }
            let commit = self.get(&format!("commits/{}", self.ref_name))?;
            let tip = field(&commit, "sha")?;
            if tip != self.sha {
                note!("{} has moved; a newer run publishes it", self.ref_name);
                return Ok(State::Superseded);
            }
            Ok(State::Current)
        }
    }

    /// The take-down job's question, which is about the pull request alone —
    /// it has no build of its own to be superseded.
    pub fn pull_request_is_open(&self) -> Result<bool> {
        let pr = self.get(&format!("pulls/{}", self.number()?))?;
        Ok(field(&pr, "state")? == "open")
    }

    fn number(&self) -> Result<&str> {
        if self.pr_number.is_empty() {
            return Err(err!("PR_NUMBER is required to ask about a pull request"));
        }
        Ok(&self.pr_number)
    }

    /// One GET against the API, whose answer must be there.
    fn get(&self, path: &str) -> Result<String> {
        match self.request("GET", path)? {
            Answer::Ok(body) => Ok(body),
            Answer::Missing => Err(err!("the API has no {path}")),
            Answer::Failed(code, body) => Err(err!(
                "could not ask the API about {path}: it answered {code}: {}",
                first_line(&body)
            )),
        }
    }

    /// The same, for a thing that legitimately may not exist yet — a Pages
    /// site that has never built. `None` is an answer; anything else is the
    /// question breaking, which is not one.
    pub fn get_if_there(&self, path: &str) -> Result<Option<String>> {
        match self.request("GET", path)? {
            Answer::Ok(body) => Ok(Some(body)),
            Answer::Missing => Ok(None),
            Answer::Failed(code, body) => Err(err!(
                "could not ask the API about {path}: it answered {code}: {}",
                first_line(&body)
            )),
        }
    }

    /// One POST, for the request that asks Pages to build again.
    ///
    /// A 409 is an answer rather than a failure: it is the API saying there
    /// is already a build for this, which is the thing being asked for. The
    /// caller waits for that one instead of spending an attempt on a second.
    pub fn post(&self, path: &str) -> Result<Posted> {
        match self.request("POST", path)? {
            Answer::Ok(_) => Ok(Posted::Queued),
            Answer::Missing => Err(err!("the API has no {path} to post to")),
            Answer::Failed(code, _) if code == "409" => Ok(Posted::AlreadyBusy),
            Answer::Failed(code, body) => Err(err!(
                "the API refused a POST to {path} with {code}: {}",
                first_line(&body)
            )),
        }
    }

    /// One request against the API.
    ///
    /// Through `curl`, which is the one thing here that is still a program
    /// rather than a library: a TLS client is the largest dependency this
    /// directory could take, and taking it would cost the property that makes
    /// the publish job a sparse checkout of one directory. `curl` is on every
    /// runner and on every machine anyone would drive this from by hand.
    ///
    /// The status code is *read* rather than left to `-f`, which is the one
    /// thing that changed when Pages joined the questions asked here: `-f`
    /// turns every HTTP answer above 399 into the same exit code, and "this
    /// site has never been built" (404) and "this token cannot see Pages"
    /// (403) are not the same answer at all — reading them as one is how a
    /// missing permission looks like a site that simply has nothing yet. So
    /// the code comes back on its own line and the caller matches on it.
    ///
    /// The token goes in a header rather than in the URL — a URL is what
    /// appears in an error message.
    fn request(&self, method: &str, path: &str) -> Result<Answer> {
        let url = format!("https://api.github.com/repos/{}/{path}", self.repo);
        let out = Run::new("curl")
            .args(["-sS", "-X", method])
            .args(["-w", "\n%{http_code}"])
            .args(["-H"])
            .arg(format!("Authorization: Bearer {}", self.token))
            .args(["-H", "Accept: application/vnd.github+json"])
            .args(["-H", "X-GitHub-Api-Version: 2022-11-28"])
            .arg(&url)
            .read()
            .map_err(|e| err!("could not reach the API about {path}: {e}"))?;
        Ok(Answer::read(&out))
    }
}

/// What asking for a build came back as.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Posted {
    Queued,
    /// There is already one, which is what was wanted.
    AlreadyBusy,
}

/// What one request came back as. Three cases and not two: see `request`.
enum Answer {
    Ok(String),
    /// 404. The caller decides whether that is an answer or a failure.
    Missing,
    Failed(String, String),
}

impl Answer {
    /// The body and the status code `-w` appended to it, split back apart.
    ///
    /// An answer with no code on the end is `curl` having written something
    /// other than what it was asked to — treated as a failure with no code,
    /// because guessing 200 there is guessing success.
    fn read(out: &str) -> Answer {
        let (body, code) = match out.rsplit_once('\n') {
            Some((body, code)) => (body.trim(), code.trim()),
            None => ("", out.trim()),
        };
        match code {
            "404" => Answer::Missing,
            c if c.starts_with('2') => Answer::Ok(body.to_string()),
            c => Answer::Failed(c.to_string(), body.to_string()),
        }
    }
}

/// Enough of an error body to be worth printing, and no more: the API's
/// answers carry documentation URLs nobody reads out of a job log.
fn first_line(body: &str) -> String {
    let line = body.lines().next().unwrap_or("").trim();
    match line.char_indices().nth(200) {
        Some((at, _)) => format!("{}...", &line[..at]),
        None => line.to_string(),
    }
}

/// A field the answer must carry. Absent is the API not having said, which is
/// the question breaking rather than an answer to it.
fn field(body: &str, path: &str) -> Result<String> {
    json::string_at(body, path)
        .ok_or_else(|| Error(format!("the API answered with no `{path}` in it")))
}

#[cfg(test)]
mod tests {
    use super::{Answer, first_line};

    /// 404 and 403 are not the same answer, and `-f` made them one.
    ///
    /// "This site has never been built" is something a caller can act on;
    /// "this token cannot see Pages" is the question breaking. Collapsing the
    /// second into the first is how a missing permission looks like a site
    /// with nothing on it yet, and gets waited out rather than reported.
    #[test]
    fn a_missing_thing_and_a_refused_one_read_differently() {
        assert!(matches!(
            Answer::read("{\"status\":\"built\"}\n200"),
            Answer::Ok(body) if body == "{\"status\":\"built\"}"
        ));
        assert!(matches!(
            Answer::read("{\"message\":\"Not Found\"}\n404"),
            Answer::Missing
        ));
        assert!(matches!(
            Answer::read("{\"message\":\"Resource not accessible\"}\n403"),
            Answer::Failed(code, _) if code == "403"
        ));
        assert!(matches!(Answer::read("\n201"), Answer::Ok(body) if body.is_empty()));
        // Nothing but a code, and nothing at all: neither is success.
        assert!(matches!(Answer::read("500"), Answer::Failed(code, _) if code == "500"));
        assert!(matches!(Answer::read(""), Answer::Failed(code, _) if code.is_empty()));
    }

    #[test]
    fn an_error_body_is_trimmed_to_something_a_log_can_hold() {
        assert_eq!(first_line("one\ntwo"), "one");
        let long = "x".repeat(500);
        assert_eq!(first_line(&long).len(), 203);
    }
}
