//! "Is this still worth publishing?", asked of GitHub rather than of the
//! branch.
//!
//! Two different questions hide here and both need asking more than once.
//! Builds run in parallel, so the order two runs reach the publish job is the
//! order their *builds* finished rather than the order their commits were
//! pushed — a slower older build would otherwise replace the live site. And a
//! pull request can close while a publish is in flight, in which case the
//! preview has already been taken down and this run would put it back.
//!
//! Asking once could close neither window: the gap is between the answer and
//! the push. So the question is asked again before every attempt at the
//! branch, which is why it is a function here rather than a step in the
//! workflow.
//!
//! Where the shell wrote this to a file and handed the publisher a command to
//! run, it is now a value the publisher holds — which is what removes the
//! third and fourth `.sh` files from the tree: two generated by heredoc into
//! `$RUNNER_TEMP`, whose only job was to translate one set of exit codes into
//! another.

use crate::json;
use crate::util::{Error, Result, Run, env_or, need_env};
use crate::{err, note};

/// What the API says about the thing this run was started for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    /// Still the newest thing to say, and still wanted.
    Current,
    /// A newer run is publishing this target; what is up there is *newer*
    /// than ours.
    Superseded,
    /// The pull request is closed; its preview should not exist at all.
    Closed,
}

/// Which question a given write to the branch is conditional on.
///
/// The shell spelled these as three small scripts and a `case` translating
/// between two vocabularies; the case that was easy to lose there — an
/// operational failure collapsing into "not closed" — is a `Result` here and
/// cannot be.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Precondition {
    /// None: publish unconditionally. Not used by the workflow; here so a
    /// publish can be driven by hand.
    Always,
    /// Publishing: proceed only while this run is still the current one.
    StillCurrent,
    /// The compensating removal after a publish: proceed only if the pull
    /// request has closed since. Superseded is *not* a reason to remove — a
    /// newer run of the same pull request owns the preview, and deleting it
    /// would take down one that is wanted.
    NowClosed,
    /// The take-down job: proceed only while the pull request is still
    /// closed. A reopened one has a `reopened` run publishing its preview
    /// behind us.
    StillClosed,
}

/// Whether the write should happen.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Wanted {
    Yes,
    StandDown,
}

impl Precondition {
    pub fn parse(name: &str) -> Result<Self> {
        match name {
            "always" | "none" => Ok(Precondition::Always),
            "still-current" => Ok(Precondition::StillCurrent),
            "now-closed" => Ok(Precondition::NowClosed),
            "still-closed" => Ok(Precondition::StillClosed),
            other => Err(err!(
                "unknown check `{other}`: expected always, still-current, now-closed or still-closed"
            )),
        }
    }

    /// Ask. An `Err` is the question *breaking* — a network blip, a rate
    /// limit, an API 500 — and reading that as "stand down" is how a
    /// deployment silently does not happen while the job reports success and
    /// leaves nothing to retry. An unanswered question is not a no.
    pub fn ask(self, api: &Api) -> Result<Wanted> {
        match self {
            Precondition::Always => Ok(Wanted::Yes),
            Precondition::StillCurrent => match api.state()? {
                State::Current => Ok(Wanted::Yes),
                State::Superseded | State::Closed => Ok(Wanted::StandDown),
            },
            Precondition::NowClosed => match api.state()? {
                State::Closed => Ok(Wanted::Yes),
                State::Current | State::Superseded => Ok(Wanted::StandDown),
            },
            Precondition::StillClosed => {
                if api.pull_request_is_open()? {
                    note!("pull request was reopened; its preview is wanted again");
                    Ok(Wanted::StandDown)
                } else {
                    Ok(Wanted::Yes)
                }
            }
        }
    }
}

/// The repository, the run, and a token to ask with.
///
/// Read from the environment once, so a missing variable is one message at
/// startup rather than a curl invocation with an empty URL in it.
pub struct Api {
    token: String,
    repo: String,
    event: String,
    pr_number: String,
    pr_head: String,
    ref_name: String,
    sha: String,
}

impl Api {
    pub fn from_env() -> Result<Self> {
        Ok(Api {
            token: need_env("GH_TOKEN")?,
            repo: need_env("GITHUB_REPOSITORY")?,
            event: env_or("GITHUB_EVENT_NAME", ""),
            pr_number: env_or("PR_NUMBER", ""),
            pr_head: env_or("PR_HEAD", ""),
            ref_name: env_or("GITHUB_REF_NAME", ""),
            sha: env_or("GITHUB_SHA", ""),
        })
    }

    fn is_pull_request(&self) -> bool {
        self.event == "pull_request"
    }

    /// The three-way answer the publisher and the compensating removal both
    /// read, and the reason they read the same one: collapsing "superseded"
    /// into "closed" is how an older superseded build deletes the newer
    /// revision's perfectly good preview.
    pub fn state(&self) -> Result<State> {
        if self.is_pull_request() {
            let pr = self.get(&format!("pulls/{}", self.number()?))?;
            let state = field(&pr, "state")?;
            if state != "open" {
                note!("pull request is closed; its preview should not exist");
                return Ok(State::Closed);
            }
            let head = field(&pr, "head.sha")?;
            let want = &self.pr_head;
            if want.is_empty() {
                return Err(err!(
                    "PR_HEAD is required to tell this run from a newer one"
                ));
            }
            if &head != want {
                note!("head has moved; a newer run publishes it");
                return Ok(State::Superseded);
            }
            Ok(State::Current)
        } else {
            if self.ref_name.is_empty() || self.sha.is_empty() {
                return Err(err!(
                    "GITHUB_REF_NAME and GITHUB_SHA are required to tell this run from a newer one"
                ));
            }
            let commit = self.get(&format!("commits/{}", self.ref_name))?;
            let tip = field(&commit, "sha")?;
            if tip != self.sha {
                note!("{} has moved; a newer run publishes it", self.ref_name);
                return Ok(State::Superseded);
            }
            Ok(State::Current)
        }
    }

    /// The take-down job's question, which is about the pull request alone —
    /// it has no build of its own to be superseded.
    pub fn pull_request_is_open(&self) -> Result<bool> {
        let pr = self.get(&format!("pulls/{}", self.number()?))?;
        Ok(field(&pr, "state")? == "open")
    }

    fn number(&self) -> Result<&str> {
        if self.pr_number.is_empty() {
            return Err(err!("PR_NUMBER is required to ask about a pull request"));
        }
        Ok(&self.pr_number)
    }

    /// One GET against the API.
    ///
    /// Through `curl`, which is the one thing here that is still a program
    /// rather than a library: a TLS client is the largest dependency this
    /// directory could take, and taking it would cost the property that makes
    /// the publish job a sparse checkout of one directory. `curl` is on every
    /// runner and on every machine anyone would drive this from by hand.
    ///
    /// `-f` so an HTTP error is a non-zero exit rather than a body that
    /// parses to nothing, and the token goes in a header rather than in the
    /// URL — a URL is what appears in an error message.
    fn get(&self, path: &str) -> Result<String> {
        let url = format!("https://api.github.com/repos/{}/{path}", self.repo);
        Run::new("curl")
            .args(["-fsSL", "-H"])
            .arg(format!("Authorization: Bearer {}", self.token))
            .args(["-H", "Accept: application/vnd.github+json"])
            .args(["-H", "X-GitHub-Api-Version: 2022-11-28"])
            .arg(&url)
            .read()
            .map_err(|e| err!("could not ask the API about {path}: {e}"))
    }
}

/// A field the answer must carry. Absent is the API not having said, which is
/// the question breaking rather than an answer to it.
fn field(body: &str, path: &str) -> Result<String> {
    json::string_at(body, path)
        .ok_or_else(|| Error(format!("the API answered with no `{path}` in it")))
}
